# Generated by Django 3.1.2 on 2020-11-09 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sod', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
