# Generated by Django 3.1.2 on 2020-11-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sod', '0004_auto_20201109_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='C:/Users/Nitcu/PycharmProjects/WebLab/static/src/default.jpg', upload_to='images/', verbose_name='Изображение'),
        ),
    ]
