# Generated by Django 3.1.2 on 2020-11-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sod', '0005_auto_20201109_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/', verbose_name='Изображение'),
        ),
    ]
