# Generated by Django 3.1.2 on 2020-11-10 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20201110_1119'),
        ('sod', '0006_auto_20201109_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sod.task')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.profile')),
            ],
        ),
    ]
