# Generated by Django 3.1.2 on 2020-11-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sod', '0007_usertasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertasks',
            old_name='id_task',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='usertasks',
            old_name='id_user',
            new_name='user',
        ),
    ]
