# Generated by Django 3.1.2 on 2020-11-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(default='images/photos/empty_photo', upload_to='images/photos/', verbose_name='Фото')),
            ],
        ),
    ]
