# Generated by Django 3.1.2 on 2020-11-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/empty_photo.jpg', upload_to='images/', verbose_name='Фото'),
        ),
    ]
